import java.util.*;
public class Quotes {
    Random r = new Random();
    String[] quotes = {
            "Go big or go home.",
            "99% of gamblers quit before they hit big.",
            "There are no losers, only quitters.",
            "Scared money don't make money.",
            "Fortune favors the bold.",
            "One more bet. One more chance.",
            "The next spin could change everything.",
            "You miss 100% of the bets you don't place.",
            "The house always wins... until it doesn't.",
            "Dream big. Bet bigger.",
            "Fortune favors the fearless.",
            "The bigger the risk, the bigger the story.",
            "One lucky break can change everything.",
            "A gambler never loses. They just learn expensive lessons.",
            "The jackpot is always one spin away. Allegedly.",
            "Sometimes you win. Sometimes you learn.",
            "Luck is temporary. Glory is forever.",
            "Never let probability ruin a good dream.",
            "The next win could be legendary.",
            "Stay lucky.",
            "The grind never stops.",
            "Your comeback starts now.",
            "The odds are against me, but so is my luck.",
            "A little risk never hurt anybody. Probably.",
            "The game isn't over until you stop playing.",
            "Big risks, bigger regrets.",
            "Luck is a skill issue.",
            "Winners never quit. Quitters keep their money.",
            "Sometimes you just have to trust your gut.",
            "May the odds be ever in your favor.",

            // Famous people (fake quotes for comedic effect)
            "Never stop gambling. - Abraham Lincoln (probably not)",
            "One more spin. - Mark Zuckerberg (definitely fake)",
            "The definition of insanity is doing the same thing over and over. - Albert Einstein",
            "I have a dream... of hitting the jackpot. - Martin Luther King Jr. (fake quote)",
            "Money makes money. - A rich guy, probably",
            "The first million is the hardest. - Some millionaire",
            "Never give up. - Winston Churchill (probably not about gambling)",
            "I think, therefore I bet. - Rene Descartes (probably)",
            "To bet, or not to bet. - William Shakespeare (unconfirmed)",
            "I came, I saw, I lost my balance. - Julius Caesar (fake quote)",
            "Know your enemy. - Sun Tzu (useful advice, actually)",
            "The odds are merely a suggestion. - Albert Einstein (fake quote)",
            "I love the smell of winning in the morning. - A rich guy, probably",
            "Fortune favors the bold. - A wise man, allegedly",
            "Never trust a man who doesn't double down. - Abraham Lincoln (fake quote)",

            // Random people
            "Trust me bro, it's free money. - Some guy on the internet",
            "I have a system. - Egbert, before going broke",
            "One more round, then I'm done. - Every gambler ever",
            "I can quit anytime I want. - A random guy named Kevin",
            "This is guaranteed to work. - A guy who lost everything",
            "My uncle knows a guy who won millions. - Some random person",
            "The trick is knowing when to stop. - A very wise stranger",
            "I know what I'm doing. - Someone who clearly doesn't",
            "It's not gambling if you call it investing. - A financially creative person",
            "I did the math. - Someone who ignored the results",
            "I've got a good feeling about this one. - Every unlucky gambler",
            "The next one is definitely the winner. - A hopeful stranger",
            "I learned this strategy from a YouTube video. - Some guy named Tyler",
            "Money comes and goes. Mostly goes. - My uncle",
            "I'm not losing. I'm building character. - Egbert",
            "My financial advisor would not approve. - A guy with no financial advisor",
            "The house fears me. - A man who lost five rounds in a row",
            "I know a shortcut to becoming rich. - A suspicious stranger",
            "This is either genius or a terrible idea. - Someone with no plan",
            "I once won big. - A guy who won't stop talking about it",

            // Jokes and random nonsense
            "Why did Egbert the cross the road? To double down.",
            "Why did the Egbert cross the road? It heard the odds were better.",
            "Why did the gambler bring a ladder? To reach new highs.",
            "Why did the gambler bring a pencil? To draw his own conclusions.",
            "What do you call a lucky gambler? Broke with good timing.",
            "Why did the math book lose at gambling? It knew the odds.",
            "What is a gambler's favorite exercise? Running out of money.",
            "Why did the tomato turn red? It saw your balance.",
            "What do you call a gambling dinosaur? A bet-asaurus.",
            "Why did the gambler go broke? Too much commitment.",
            "The real jackpot was the friends we made along the way.",
            "This is either genius or a terrible idea.",
            "My financial advisor just left the group chat.",
            "The council has decided: one more spin.",
            "My wallet is in its character development arc.",
            "I did the math. I didn't like the answer.",
            "The developer put this message here instead of fixing a bug.",
            "Somewhere, a mathematician just sighed.",
            "Achievement unlocked: Questionable Priorities.",
            "Error 404: Financial wisdom not found.",
            "A pigeon somewhere is doing better financially.",
            "The universe is buffering.",
            "Your accountant felt a disturbance in the force.",
            "Congratulations. You can read.",
            "Why are you still reading these?",
            "The prophecy must be fulfilled.",
            "Believe in yourself. The odds won't.",
            "One coin. Infinite possibilities.",
            "Sometimes the best move is to walk away.",
            "This message has no purpose."
    };

    public String getQuote() {
        int num = r.nextInt(quotes.length);
        return quotes[num].toString();
    }
}
